# Generated by Django 3.2.5 on 2021-08-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default='asdadasdasdada', max_length=500),
        ),
    ]
