# Generated by Django 3.2.5 on 2021-08-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
