# Generated by Django 3.2.5 on 2021-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20210803_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='day',
            field=models.DateField(max_length=100),
        ),
    ]
