# Generated by Django 3.2.5 on 2021-08-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_order_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
