# Generated by Django 3.2.5 on 2021-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
