# Generated by Django 3.2.5 on 2021-08-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20210803_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
