# Generated by Django 3.2.5 on 2021-08-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
