# Generated by Django 3.2.5 on 2021-07-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='street food', max_length=100, unique=True),
        ),
    ]
