# Generated by Django 3.2.5 on 2021-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_amount',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
