# Generated by Django 3.2.5 on 2021-07-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
